name: Lisa Harvey
favicon: null
layout_spectrum: 0.97177554666996
typography_spectrum: 0.08407228905707598
title: "I'll think of something."
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8812159795779735
  lightness: 0.245317657943815
  saturation: 0.28183101234026253
  rhythmicContrast: 0.45941160526126623
purpose: []
