name: Lisa Harvey
favicon: null
layout_spectrum: 0.27617
typography_spectrum: 0.61071
title: "I'll think of something."
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.125
  lightness: 0.5625
  saturation: 0.5625
  rhythmicContrast: 0.45941160526126623
purpose: []
